version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo-patch-minor:
        update-types: ["patch", "minor"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "dtolnay/rust-toolchain"
    groups:
      actions-patch-minor:
        update-types: ["patch", "minor"]
