//! Historical layout fixture used only by existing regression tests.

use super::model::{ElementId, ElementKind};

#[cfg(test)]
pub(super) fn legacy_rows() -> Vec<(ElementId, ElementKind, &'static str, &'static str)> {
    vec![
        (
            ElementId::StartWithWindows,
            ElementKind::Toggle,
            "Start with Windows",
            "Launch at sign-in",
        ),
        (
            ElementId::StartHotkeysEnabled,
            ElementKind::Toggle,
            "Shortcuts enabled",
            "Enable global actions",
        ),
        (
            ElementId::MicHotkey,
            ElementKind::Hotkey,
            "Mute microphone",
            "Toggle mute",
        ),
        (
            ElementId::OutputHotkey,
            ElementKind::Hotkey,
            "Mute speakers",
            "Toggle mute",
        ),
        (
            ElementId::ForegroundHotkey,
            ElementKind::Hotkey,
            "Mute current app",
            "Toggle app audio",
        ),
        (
            ElementId::CycleInputHotkey,
            ElementKind::Hotkey,
            "Next microphone",
            "Switch to the next selected microphone",
        ),
        (
            ElementId::CycleOutputHotkey,
            ElementKind::Hotkey,
            "Next speaker",
            "Switch to the next selected speaker",
        ),
        (
            ElementId::ForegroundVolumeUpHotkey,
            ElementKind::Hotkey,
            "Current app volume up",
            "Raise the current app by five percent",
        ),
        (
            ElementId::ForegroundVolumeDownHotkey,
            ElementKind::Hotkey,
            "Current app volume down",
            "Lower the current app by five percent",
        ),
        (
            ElementId::InputDevice,
            ElementKind::Value,
            "Microphone",
            "Input device",
        ),
        (
            ElementId::OutputDevice,
            ElementKind::Value,
            "Speakers",
            "Output device",
        ),
        (
            ElementId::InputAllowlist,
            ElementKind::Value,
            "Microphone cycling",
            "Input devices",
        ),
        (
            ElementId::OutputAllowlist,
            ElementKind::Value,
            "Speaker cycling",
            "Output devices",
        ),
        (
            ElementId::InputRole,
            ElementKind::Value,
            "Input role",
            "Windows role",
        ),
        (
            ElementId::OutputRole,
            ElementKind::Value,
            "Output role",
            "Windows role",
        ),
        (
            ElementId::DisplayProfilesEnabled,
            ElementKind::Toggle,
            "Display profiles",
            "Save arrangements",
        ),
        (
            ElementId::DisplayProfile,
            ElementKind::Value,
            "Display profile",
            "Selected profile",
        ),
        (
            ElementId::DisplayProfileHotkey,
            ElementKind::Hotkey,
            "Profile shortcut",
            "Activate profile",
        ),
        (
            ElementId::DisplayOutputs,
            ElementKind::Value,
            "Which displays",
            "Selected routes",
        ),
        (
            ElementId::DisplayTopology,
            ElementKind::Value,
            "How they work",
            "Topology",
        ),
        (
            ElementId::DisplayRoute,
            ElementKind::Value,
            "Display output",
            "Route",
        ),
        (
            ElementId::EditDisplayRoute,
            ElementKind::Action,
            "Edit output",
            "Advanced values",
        ),
        (
            ElementId::NewDisplayProfile,
            ElementKind::ButtonPrimary,
            "New profile",
            "Create",
        ),
        (
            ElementId::UpdateDisplayProfile,
            ElementKind::Action,
            "Update profile",
            "Capture",
        ),
        (
            ElementId::RenameDisplayProfile,
            ElementKind::Action,
            "Rename profile",
            "Change name",
        ),
        (
            ElementId::DuplicateDisplayProfile,
            ElementKind::Action,
            "Duplicate profile",
            "Copy",
        ),
        (
            ElementId::TestApplyDisplayProfile,
            ElementKind::ButtonPrimary,
            "Test profile",
            "Try safely",
        ),
        (
            ElementId::DeleteDisplayProfile,
            ElementKind::ButtonDanger,
            "Delete profile",
            "Remove",
        ),
        (
            ElementId::KeepDisplayChange,
            ElementKind::ButtonPrimary,
            "Keep display setup",
            "Confirm",
        ),
        (
            ElementId::UndoDisplayChange,
            ElementKind::ButtonSecondary,
            "Revert display setup",
            "Restore",
        ),
        (
            ElementId::DesktopsEnabled,
            ElementKind::Toggle,
            "Workspace shortcuts",
            "Enable workspace actions",
        ),
        (
            ElementId::WinNumberEnabled,
            ElementKind::Toggle,
            "Desktop numbers",
            "Switch desktops",
        ),
        (
            ElementId::DesktopNumberModifier,
            ElementKind::Value,
            "Desktop modifier",
            "Modifier",
        ),
        (
            ElementId::MoveDesktopModifier,
            ElementKind::Value,
            "Move and follow",
            "Modifier",
        ),
        (
            ElementId::SilentMoveDesktopModifier,
            ElementKind::Value,
            "Move quietly",
            "Modifier",
        ),
        (
            ElementId::PreviousDesktopHotkey,
            ElementKind::Hotkey,
            "Previous desktop",
            "Go back",
        ),
        (
            ElementId::AssignScratchpadHotkey,
            ElementKind::Hotkey,
            "Move window to Special Desktop",
            "Move",
        ),
        (
            ElementId::ToggleScratchpadHotkey,
            ElementKind::Hotkey,
            "Open Special Desktop",
            "Open",
        ),
        (
            ElementId::OverlayEnabled,
            ElementKind::Toggle,
            "Show overlay",
            "Status card",
        ),
        (
            ElementId::OverlayAppearance,
            ElementKind::Value,
            "Appearance",
            "System or theme",
        ),
        (
            ElementId::OverlayExternalChanges,
            ElementKind::Toggle,
            "Windows audio changes",
            "Show changes",
        ),
        (
            ElementId::OverlayPosition,
            ElementKind::Value,
            "Position",
            "Overlay location",
        ),
        (
            ElementId::OverlayMonitor,
            ElementKind::Value,
            "Monitor",
            "Overlay monitor",
        ),
        (
            ElementId::OverlayDuration,
            ElementKind::Slider,
            "Duration",
            "How long it stays",
        ),
        (
            ElementId::OverlayOpacity,
            ElementKind::Slider,
            "Opacity",
            "Transparency",
        ),
        (
            ElementId::OverlayScale,
            ElementKind::Slider,
            "Size",
            "Overlay size",
        ),
        (
            ElementId::OverlayPreview,
            ElementKind::Action,
            "Preview",
            "Show overlay",
        ),
        (
            ElementId::DebugLogging,
            ElementKind::Toggle,
            "Debug logging",
            "Temporary",
        ),
        (
            ElementId::OpenConfigFolder,
            ElementKind::Action,
            "Open folder",
            "Configuration",
        ),
        (
            ElementId::ResetSettings,
            ElementKind::ButtonDanger,
            "Reset",
            "Restore defaults",
        ),
    ]
}
