//! Core Audio callbacks. They enqueue compact worker commands only; no UI or
//! endpoint manipulation occurs inside COM callback methods (spec §25).

use std::sync::mpsc::Sender;

use windows::core::{implement, PCWSTR};
use windows::Win32::Foundation::PROPERTYKEY;
use windows::Win32::Media::Audio::Endpoints::{
    IAudioEndpointVolumeCallback, IAudioEndpointVolumeCallback_Impl,
};
use windows::Win32::Media::Audio::{
    AUDIO_VOLUME_NOTIFICATION_DATA, DEVICE_STATE, EDataFlow, ERole, IMMNotificationClient,
    IMMNotificationClient_Impl,
};

use crate::audio::controller::{AudioCommand, EndpointFlow};
use crate::audio::devices::AUDIO_EVENT_CONTEXT;

/// Command (if any) generated by an endpoint volume callback (#19).
/// `None` for self-originated changes: our own SetMute passes
/// AUDIO_EVENT_CONTEXT and the mutating path already publishes state.
pub(crate) fn notify_command(
    flow: EndpointFlow,
    event_context: windows_core::GUID,
) -> Option<AudioCommand> {
    if event_context == AUDIO_EVENT_CONTEXT {
        None
    } else {
        Some(AudioCommand::RefreshEndpoint(flow))
    }
}

#[implement(IMMNotificationClient)]
pub struct DeviceNotificationClient {
    sender: Sender<AudioCommand>,
}

impl DeviceNotificationClient {
    pub fn create(sender: Sender<AudioCommand>) -> IMMNotificationClient {
        Self { sender }.into()
    }
}

impl IMMNotificationClient_Impl for DeviceNotificationClient_Impl {
    fn OnDeviceStateChanged(
        &self,
        _device_id: &PCWSTR,
        _new_state: DEVICE_STATE,
    ) -> windows::core::Result<()> {
        let _ = self.sender.send(AudioCommand::RefreshAll);
        Ok(())
    }

    fn OnDeviceAdded(&self, _device_id: &PCWSTR) -> windows::core::Result<()> {
        let _ = self.sender.send(AudioCommand::RefreshAll);
        Ok(())
    }

    fn OnDeviceRemoved(&self, _device_id: &PCWSTR) -> windows::core::Result<()> {
        let _ = self.sender.send(AudioCommand::RefreshAll);
        Ok(())
    }

    fn OnDefaultDeviceChanged(
        &self,
        _flow: EDataFlow,
        _role: ERole,
        _default_device_id: &PCWSTR,
    ) -> windows::core::Result<()> {
        let _ = self.sender.send(AudioCommand::RefreshAll);
        Ok(())
    }

    fn OnPropertyValueChanged(
        &self,
        _device_id: &PCWSTR,
        _key: &PROPERTYKEY,
    ) -> windows::core::Result<()> {
        let _ = self.sender.send(AudioCommand::RefreshAll);
        Ok(())
    }
}

#[implement(IAudioEndpointVolumeCallback)]
pub struct EndpointVolumeClient {
    sender: Sender<AudioCommand>,
    flow: EndpointFlow,
}

impl EndpointVolumeClient {
    pub fn create(
        sender: Sender<AudioCommand>,
        flow: EndpointFlow,
    ) -> IAudioEndpointVolumeCallback {
        Self { sender, flow }.into()
    }
}

impl IAudioEndpointVolumeCallback_Impl for EndpointVolumeClient_Impl {
    fn OnNotify(
        &self,
        notification: *mut AUDIO_VOLUME_NOTIFICATION_DATA,
    ) -> windows::core::Result<()> {
        // SAFETY: the shell guarantees a valid notification record for the
        // duration of this callback.
        let context = unsafe { (*notification).guidEventContext };
        if let Some(command) = notify_command(self.flow, context) {
            let _ = self.sender.send(command);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use windows::core::GUID;

    #[test]
    fn own_context_notifications_are_dropped() {
        // #19: WinShort's own mute writes must not re-enter as external events.
        assert_eq!(
            notify_command(EndpointFlow::Render, AUDIO_EVENT_CONTEXT),
            None
        );
        let foreign = GUID::from_u128(0x1234_5678_9abc_def0_1122_3344_5566_7788);
        assert!(matches!(
            notify_command(EndpointFlow::Capture, foreign),
            Some(AudioCommand::RefreshEndpoint(_))
        ));
    }
}
